# Linear Regression

### Content:
- Regressing House Price Change on Covid Mortality Rates
- Same Regression, Controlled for State

In [1]:
#import libraries
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [2]:
#import merged dataset
df = pd.read_pickle('/Users/kimballwightman/Desktop/Projects/Covid & House Prices Analysis/02 Data/Prepared Data/df_merge.pkl')

In [3]:
df.head()

,fips,county,state,deaths,PopTotal,zip_three,index change,state_fips,deaths_pc
0,1001.0,Autauga,Alabama,5683.0,58805,360,16.7625,01,9664.144205
1,1001.0,Autauga,Alabama,5683.0,58805,367,23.9850,01,9664.144205
2,1003.0,Baldwin,Alabama,12446.0,231767,364,23.9850,01,5370.048368
3,1003.0,Baldwin,Alabama,12446.0,231767,365,34.1150,01,5370.048368
4,1005.0,Barbour,Alabama,2035.0,25223,360,16.7625,01,8068.033144

### Regressing House Price Change on Covid Mortality Rates

In [4]:
#run linear regression of inex_change on deaths_pc
X = df['deaths_pc'].values.reshape(-1,1)
y = df['index change'].values.reshape(-1,1)

In [5]:
X = sm.add_constant(X)

In [6]:
#use heteroskadisticity-robust covariance type
reg1 = sm.OLS(y,X).fit(cov_type='HC1')

In [7]:
print(reg1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     52.26
Date:                Wed, 10 Aug 2022   Prob (F-statistic):           5.33e-13
Time:                        14:01:47   Log-Likelihood:                -29620.
No. Observations:                7546   AIC:                         5.924e+04
Df Residuals:                    7544   BIC:                         5.926e+04
Df Model:                           1
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         30.3185      0.199    152.379      0.000      29.929      30.708
x1         -8.698e-05    1.2e-05     -7.229      0.000      -0.000   -6.34e-05
==============================================================================
Omnibus:                     2479.792   Durbin-Watson:                   0.534
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8377.649
Skew:                           1.662   Prob(JB):                         0.00
Kurtosis:                       6.949   Cond. No.                     2.28e+04
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.28e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

### Same Regression, Controlled for State

In [8]:
#create dummy variables for each state code
df_dummies = pd.get_dummies(df, prefix = ['State'], columns = ['state_fips'], drop_first=True)

In [9]:
df_dummies.head()

,fips,county,state,deaths,PopTotal,zip_three,index change,deaths_pc,State_02,State_04,...,State_46,State_47,State_48,State_49,State_50,State_51,State_53,State_54,State_55,State_56
0,1001.0,Autauga,Alabama,5683.0,58805,360,16.7625,9664.144205,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001.0,Autauga,Alabama,5683.0,58805,367,23.9850,9664.144205,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1003.0,Baldwin,Alabama,12446.0,231767,364,23.9850,5370.048368,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1003.0,Baldwin,Alabama,12446.0,231767,365,34.1150,5370.048368,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1005.0,Barbour,Alabama,2035.0,25223,360,16.7625,8068.033144,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df_dummies.columns

Index(['fips', 'county', 'state', 'deaths', 'PopTotal', 'zip_three',
       'index change', 'deaths_pc', 'State_02', 'State_04', 'State_05',
       'State_06', 'State_08', 'State_09', 'State_10', 'State_11', 'State_12',
       'State_13', 'State_15', 'State_16', 'State_17', 'State_18', 'State_19',
       'State_20', 'State_21', 'State_22', 'State_23', 'State_24', 'State_25',
       'State_26', 'State_27', 'State_28', 'State_29', 'State_30', 'State_31',
       'State_32', 'State_33', 'State_34', 'State_35', 'State_36', 'State_37',
       'State_38', 'State_39', 'State_40', 'State_41', 'State_42', 'State_44',
       'State_45', 'State_46', 'State_47', 'State_48', 'State_49', 'State_50',
       'State_51', 'State_53', 'State_54', 'State_55', 'State_56'],
      dtype='object')

In [12]:
X = df_dummies[['deaths_pc', 'State_02', 'State_04',
       'State_05', 'State_06', 'State_08', 'State_09', 'State_10', 'State_11',
       'State_12', 'State_13', 'State_15', 'State_16', 'State_17', 'State_18',
       'State_19', 'State_20', 'State_21', 'State_22', 'State_23', 'State_24',
       'State_25', 'State_26', 'State_27', 'State_28', 'State_29', 'State_30',
       'State_31', 'State_32', 'State_33', 'State_34', 'State_35', 'State_36',
       'State_37', 'State_38', 'State_39', 'State_40', 'State_41', 'State_42',
       'State_44', 'State_45', 'State_46', 'State_47', 'State_48', 'State_49',
       'State_50', 'State_51', 'State_53', 'State_54', 'State_55', 'State_56']].values

In [13]:
X

array([[9.66414421e+03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.66414421e+03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.37004837e+03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.45476773e+03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.81782694e+04, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.08218777e+03, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [14]:
X = sm.add_constant(X)

In [15]:
reg2 = sm.OLS(y,X).fit(cov_type='HC1')

In [16]:
print(reg2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.654
Model:                            OLS   Adj. R-squared:                  0.652
Method:                 Least Squares   F-statistic:                     3157.
Date:                Wed, 10 Aug 2022   Prob (F-statistic):               0.00
Time:                        14:02:47   Log-Likelihood:                -25642.
No. Observations:                7546   AIC:                         5.139e+04
Df Residuals:                    7494   BIC:                         5.175e+04
Df Model:                          51
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         25.1518      0.423     59.487      0.000      24.323      25.981
x1         -9.197e-05    1.1e-05     -8.346      0.000      -0.000   -7.04e-05
x2            -4.9323      0.686     -7.189      0.000      -6.277      -3.588
x3            32.2252      1.837     17.538      0.000      28.624      35.826
x4            -2.5815      0.515     -5.017      0.000      -3.590      -1.573
x5            18.8626      1.075     17.550      0.000      16.756      20.969
x6            22.6001      0.679     33.297      0.000      21.270      23.930
x7            -0.6597      0.707     -0.934      0.350      -2.045       0.725
x8             6.2282      1.908      3.264      0.001       2.488       9.968
x9            17.4208      0.392     44.418      0.000      16.652      18.189
x10           23.8066      0.840     28.336      0.000      22.160      25.453
x11            6.7952      0.582     11.684      0.000       5.655       7.935
x12           -0.7218      2.014     -0.358      0.720      -4.669       3.225
x13           47.9884      1.501     31.976      0.000      45.047      50.930
x14           -8.7405      0.426    -20.526      0.000      -9.575      -7.906
x15            1.9210      0.417      4.603      0.000       1.103       2.739
x16           -4.2793      0.423    -10.109      0.000      -5.109      -3.450
x17           -1.8005      0.446     -4.041      0.000      -2.674      -0.927
x18            1.1506      0.474      2.425      0.015       0.221       2.080
x19           -7.7111      0.567    -13.600      0.000      -8.822      -6.600
x20            0.9907      0.553      1.791      0.073      -0.094       2.075
x21            2.7280      0.704      3.875      0.000       1.348       4.108
x22            3.1775      0.653      4.867      0.000       1.898       4.457
x23            4.2917      0.529      8.105      0.000       3.254       5.329
x24            5.2793      0.469     11.245      0.000       4.359       6.199
x25           -4.4030      0.467     -9.436      0.000      -5.318      -3.488
x26            4.0471      0.452      8.957      0.000       3.161       4.933
x27           33.8183      1.396     24.225      0.000      31.082      36.554
x28            0.3791      0.411      0.921      0.357      -0.427       1.186
x29           21.0178      0.895     23.485      0.000      19.264      22.772
x30           11.7870      1.053     11.192      0.000       9.723      13.851
x31           15.7733      1.249     12.632      0.000      13.326      18.221
x32           -0.2256      0.640     -0.353      0.724      -1.479       1.028
x33            2.4095      0.699      3.449      0.001       1.040       3.779
x34            8.1053      0.625     12.959      0.000       6.879       9.331
x35           -8.4744      0.496    -17.070      0.000      -9.447      -7.501
x36           -0.4786      0.454     -1.055      0.292      -1.368       0.411
x37           -1.0609      0.486     -2.185      0.029      -2.013      -0.109
x38           28.2386      1.652     17.091      0.000      25.000      31.477
x39           -0.9426      0.488     -1.932      0.053      -1.899       0.014
x40           12.3586      1.879      6.576      0.000       8.675      16.042
x41            6.0566      0.849      7.131      0.000       4.392       7.721
x42            9.9661      0.809     12.312      0.000       8.380      11.553
x43           15.8389      0.603     26.288      0.000      14.658      17.020
x44           11.2481      0.647     17.381      0.000       9.980      12.517
x45           37.2297      0.621     59.985      0.000      36.013      38.446
x46            0.6793      0.907      0.749      0.454      -1.099       2.458
x47            2.9341      0.451      6.503      0.000       2.050       3.819
x48           25.7049      0.807     31.861      0.000      24.124      27.286
x49           -8.2329      0.455    -18.113      0.000      -9.124      -7.342
x50            2.1855      0.565      3.870      0.000       1.079       3.292
x51            7.0437      1.321      5.333      0.000       4.455       9.633
==============================================================================
Omnibus:                     2881.407   Durbin-Watson:                   1.483
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            50682.115
Skew:                           1.370   Prob(JB):                         0.00
Kurtosis:                      15.397   Cond. No.                     1.42e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.42e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [17]:
#summary statistics
df.describe().apply(lambda s: s.apply(lambda x: format(x, 'g')))

            deaths    PopTotal zip_three index change deaths_pc
count         7546        7546      7546         7546      7546
mean       35028.6      200404   522.897      29.3264   11405.1
std         115846      656575   224.109      12.3014   11610.3
min              0          64       100      -6.6175         0
25%            748     14786.5       335       21.715    3668.3
50%           2674       37548       508      25.8475   7430.69
75%          11853      132813       703      33.0038   14705.6
max    1.33198e+06  1.0014e+07       999       103.92    105261